version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/orderservice
      - MONGO_DB_PASSWORD=orders_password
    networks:
      - task-network
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - ORDERS_PASSWORD=orders_password
    networks:
      - task-network
    restart: unless-stopped

volumes:
  mongodb-data:

networks:
  task-network:
    driver: bridge